<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net472;net6.0;netstandard2.0</TargetFrameworks>
        <LangVersion>14</LangVersion>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup>
        <PackageId>MorseCode.StagedConstruction</PackageId>
        <MinVerTagPrefix>morsecode-stagedconstruction-</MinVerTagPrefix>
        <Product>MorseCode.StagedConstruction</Product>
        <Title>MorseCode.StagedConstruction</Title>
        <Description>Construction of immutable objects in ordered stages, with no access to a partly built object.</Description>
        <PackageIcon>MorseCode.png</PackageIcon>
        <AssemblyName>MorseCode.StagedConstruction</AssemblyName>
        <RootNamespace>MorseCode.StagedConstruction</RootNamespace>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Constructor.cs"/>
        <Compile Include="Constructor.Generic.cs"/>
        <Compile Include="SelectedConstruct.cs"/>
        <Compile Include="SingleUse.cs"/>
        <Compile Include="Stage.cs"/>
        <Compile Include="Stage.Generic.cs"/>
        <Compile Include="StageContinuation.cs"/>
        <Compile Include="StageFromBody.cs"/>
        <Compile Include="ValuesConstruct.cs"/>
    </ItemGroup>

    <ItemGroup>
      <None Include="..\..\logo\MorseCode.png" Pack="true" PackagePath="\">
        <Link>MorseCode.png</Link>
      </None>
    </ItemGroup>

</Project>
